# Generated by Django 3.2.4 on 2021-06-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Coporate_Headoffice', 'Coporate Headoffice'), ('Operation_Deparment', 'Operation Deparment'), ('Work_Station', 'Work Station'), ('Marketing_Division', 'Marketing Division')], default='Coporate_Headoffice', max_length=100)),
                ('incident_des', models.TextField(max_length=500)),
                ('incident_date', models.DateField(max_length=100)),
                ('incident_time', models.TimeField(max_length=100)),
                ('incident_location', models.TextField(max_length=200)),
                ('initial_severity', models.TextField(max_length=500)),
                ('suspected_cause', models.TextField(max_length=500)),
                ('actions_taken', models.TextField(max_length=500)),
                ('sub_type_incident', models.CharField(max_length=100)),
                ('reported_by', models.TextField(max_length=100)),
            ],
        ),
    ]
