# Generated by Django 3.2.4 on 2021-06-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentmodel',
            old_name='actions_taken',
            new_name='action_taken',
        ),
        migrations.RenameField(
            model_name='incidentmodel',
            old_name='initial_severity',
            new_name='incident_severity',
        ),
    ]
